ErrorHandlerandAuthetication/Models/DataModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ErrorHandlerandAuthetication.Models
{
    public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }

        public string? UserName { get; set; }

        public string? Account { get; set; }
        public string? Password { get; set; }

        public string? GroupId { get; set; }
    }

    public class Group
    {
        [Key]
        public string? GroupId { get; set; }

        public string? GroupName { get; set; }
    }

    public class MenuCode
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int FunctionSeq { get; set; }
        
        public string? MainFuncionName { get; set; }
        public string? DetailFunctionName { get; set; }

        public string? GroupId { get; set; }
    }
}

ErrorHandlerandAuthetication/Models/ProjectModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ErrorHandlerandAuthetication.Models
{
    public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }

        public string? UserName { get; set; }

        public string? Account { get; set; }
        public string? Password { get; set; }

        public string? GroupId { get; set; }
    }

    public class Group
    {
        [Key]
        public string? GroupId { get; set; }

        public string? GroupName { get; set; }
    }

    public class MenuCode
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int FunctionSeq { get; set; }
        
        public string? MainFuncionName { get; set; }
        public string? DetailFunctionName { get; set; }

        public string? GroupId { get; set; }
    }
}

ErrorHandlerandAuthetication/Controllers/DownloadController.cs
using Aspose.Words;
using Microsoft.AspNetCore.Mvc;

namespace ErrorHandlerandAuthetication.Controllers
{
    public class DownloadController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public DownloadController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GenerateWordDocumnet([FromBody] Dictionary<string, string> rowData)
        {
            try
            {
                // 抓取範本
                var fileName = rowData.GetValueOrDefault("FileName");
                var printTemplete = $"{fileName}.docx";

                // 輸出檔名
                var outTemplete = $"{fileName}_{DateTime.Now:yyyyMMddHHmmss}.pdf";

                // 讀取現有的Word檔案
                var templatePath = Path.Combine(_webHostEnvironment.ContentRootPath, "App_Data", printTemplete);
                Document doc = new Document(templatePath);

                // 取代WORD中的位置
                foreach (var placeValue in rowData)
                {
                    var placehilder = $"{{{placeValue.Key}}}";
                    doc.Range.Replace(placehilder, placeValue.Value);
                }

                // 儲存生成的文件
                var outputPath = Path.Combine(_webHostEnvironment.ContentRootPath, "App_Data", outTemplete);
                doc.Save(outputPath, Aspose.Words.SaveFormat.Pdf);

                // 返回生成的文件路徑給前端
                return Json(new { FileName = outTemplete });
            }
            catch(Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        public IActionResult DownloadFile(string fileName)
        {
            // 設定檔案路徑
            var filePath = Path.Combine(_webHostEnvironment.ContentRootPath, "App_Data", fileName);

            // 返回文件給前端進行下載
            return PhysicalFile(filePath, "application/octet-stream", fileName);
        }
    }
}

ErrorHandlerandAuthetication/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

namespace ErrorHandlerandAuthetication.Controllers
{
    public class ErrorController : Controller
    {
        private readonly ILogger<ErrorController> _logger;

        public ErrorController(ILogger<ErrorController> logger)
        {
            _logger = logger;   
        }

        public IActionResult Index()
        {
            _logger.LogInformation("嗨嗨");
            throw new Exception("Error");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(string? errMessage)
        {
            if (!string.IsNullOrEmpty(errMessage))
            {
                //Tuple<string>? message = JsonConvert.DeserializeObject<Tuple<string>>(errMessage);
                ViewBag.ErrMessage = JsonConvert.DeserializeObject<string>(errMessage);
            }
            return View();
        }
    }
}

ErrorHandlerandAuthetication/Controllers/LoginController.cs
using AutoMapper;
using Dapper;
using ErrorHandlerandAuthetication.DBContexts;
using ErrorHandlerandAuthetication.Helper;
using ErrorHandlerandAuthetication.Models;
using ErrorHandlerandAuthetication.ProjModels;
using ErrorHandlerandAuthetication.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Data.Common;

namespace ErrorHandlerandAuthetication.Controllers
{
    public class LoginController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ProjectContext _context;

        public LoginController(IMapper mapper,ProjectContext context)
        {
            _mapper = mapper;
            _context = context;
        }

        public IActionResult Index(string? authMessage= "")
        {
            ViewBag.AuthMessage = authMessage;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginUser loginUser) 
        {
            User? user = await _context.Users.FirstOrDefaultAsync(x => x.Account == loginUser.Username && x.Password == loginUser.Password);
            if (user == null)
                return RedirectToAction("Index", "Login", new { ErrorMsg = "this person unfound" });
            UserViewModel userViewModel = _mapper.Map<UserViewModel>(user);


            UserInfo? userInfo = null;
            using(DbConnection conn = _context.Database.GetDbConnection())
            {
                DynamicParameters parameters = new DynamicParameters();
                parameters.Add("UserID", userViewModel.UserId);
                userInfo = await conn.QueryFirstOrDefaultAsync<UserInfo>("UserInfo_SP", parameters, commandType: CommandType.StoredProcedure);
            }
            HttpContext.Session.Clear();
            HttpContext.SetObjectTOSession<UserInfo>("userInfo", userInfo);

            return RedirectToAction("HomePage","Login");
        }

        public IActionResult HomePage()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Login");
        }
    }
}

ErrorHandlerandAuthetication/Controllers/Test2Controller.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ErrorHandlerandAuthetication.Controllers
{
    [Authorize(Policy = "MenuPolicy")]
    public class Test2Controller : Controller
    {
        public IActionResult Index1()
        {
            return View();
        }

        public IActionResult Index2()
        {
            return View();
        }
    }
}

ErrorHandlerandAuthetication/Controllers/TestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ErrorHandlerandAuthetication.Controllers
{
    [Authorize(Policy = "MenuPolicy")]
    public class TestController : Controller
    {
        
        public IActionResult Index1()
        {
            return View();
        }
    }
}

ErrorHandlerandAuthetication/Views/Download/Index.cshtml
H1<input id="H1" />
T1<input id="T1" />
N1<input id="N1" />

<button onclick="DownloadWord()">下載Word</button>

<script>
   function DownloadWord(){
        let rowData = {};

        rowData["H1"] = document.getElementById('H1').value;
        rowData["T1"] = document.getElementById('T1').value;
        rowData["N1"] = document.getElementById('N1').value;
        rowData["FileName"] = "測試";

        let formData = new FormData();
        formData.append("rowData", JSON.stringify(rowData));

        // 呼叫 GenerateWordDocument 動作
        fetch("/Download/GenerateWordDocumnet", {
            method: "Post",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(rowData),
        })
            .then(response => response.json())
            .then(data => {
                let fileName = data.fileName;
                let link = document.createElement("a");
                link.href = `/Download/DownloadFile?fileName=${fileName}`;
                link.download = fileName;
                // 將鏈接添加到document並點擊
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link)
            })
            .catch(error => {
                console.error(error);
            })
   }
</script>

ErrorHandlerandAuthetication/Views/Login/HomePage.cshtml
<h1>HomePage</h1>

@Html.ActionLink("download","Index","Download")

ErrorHandlerandAuthetication/Views/Login/Index.cshtml
@{
    Layout = "_LogLayout";
}

<form action="/Login/Index" method="post">
  <div class="imgcontainer">
   @* <img src="img_avatar2.png" alt="Avatar" class="avatar">*@
  </div>

  <div class="container">
    <label for="Username"><b>Username</b></label>
    <input type="text" value="tnfe01" name="Username" required>

    <label for="Password"><b>Password</b></label>
    <input type="password" value="@@a0123456789" name="Password" required>

    <button type="submit">Login</button>
  </div>

</form>

@section Scripts{
    <script>
        let authMessage = '@ViewBag.authMessage';
        window.onload = function(){
            if (authMessage != '')
                alert(authMessage);
        }
    </script>
}

ErrorHandlerandAuthetication/Views/Shared/Components/LayoutHeader/Default.cshtml
@using ErrorHandlerandAuthetication.ProjModels

@model List<HeaderInfo>




<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ErrorHandlerandAuthe</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                @foreach(var headerInfo in Model)
                {
                    <li class="nav-item dropdown">
                        <a style="color:black" class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @headerInfo.ParentCode
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                            @foreach(var funcInfo in headerInfo.FuncInfos)
                            {
                                <li><a class="dropdown-item" href="@funcInfo.Url">@funcInfo.FuncCode</a></li>
                            }
                        </ul>
                    </li>
                }
            </ul>
            <form class="d-flex">
                <span>@ViewBag.UserName</span>&nbsp;&nbsp;
                <button class="btn btn-outline-success" type="submit">
                    <a href="/Login/Logout" style="color:black; text-decoration:none;">Logout</a>
                </button>                
            </form>
        </div>
    </div>
</nav>

ErrorHandlerandAuthetication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ErrorHandlerandAuthetication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ErrorHandlerandAuthetication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ErrorHandlerandAuthetication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ErrorHandlerandAuthetication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ErrorHandlerandAuthetication/Views/Shared/_LogLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ErrorHandlerandAuthetication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ErrorHandlerandAuthetication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
        <span>ErrorHandlerandAuthetication</span>
        </div>
        </nav>       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ErrorHandlerandAuthetication 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ErrorHandlerandAuthetication/Views/Test/Index1.cshtml
<h1>index1</h1>

ErrorHandlerandAuthetication/Views/Test/Index2.cshtml
<h1>index2</h1>

ErrorHandlerandAuthetication/Views/Test2/Index1.cshtml
<h1>Test2-Index1</h1>

ErrorHandlerandAuthetication/Views/Test2/Index2.cshtml
<h1>Test2-Index2</h1>